### ISSUE TITLE
An empty file is opened (for all commands)

### ISSUE THREAD

**Issue by ghost** [fabiospampinato/vscode-git-history#1]
Each of these commands:
- Git: Open File at Commit
- Git: Open File at Commit to the Side
- Git: Diff File at Commit
- Git: Diff File at Commit against Current

open an empty file.

VSCode version: 1.26.1
Extension version: 2.0.1
Git version: 2.17.1.windows.2
SO: Windows 10

**Comment by fabiospampinato** [comment]
Can you write some reproducible steps?

**Comment by ghost** [comment]
I have found a solution.
The issue is relative to the git show command: it not resolve path if the path contains backslash `\` (in Windows style).
Replacing backslash `\` with slash `/` resolve the problem.

**Comment by fabiospampinato** [comment]
Thanks for the PR, I've published v2.0.2.
