### ISSUE TITLE
Git diff issue..

### ISSUE THREAD

**Issue by zigang93** [fabiospampinato/vscode-git-history#3]
error msg: `Couldn't get this commit's content, please report the error`

when i try to diff some file from commit history.. 
this error show up.. commit from last 3 month..
if i diff to last week commit.. it work.. just the 3 month ago commit not working.

**Comment by fabiospampinato** [comment]
That's weird, can you perhaps link the repository you're trying this with? If that's open sourced. I would need to reproduce this in order to fix it.

**Comment by zigang93** [comment]
@fabiospampinato unfortunately, the source code is not open source and I not allow to share too. Today, i was trying to reproduce the error but find out that it work agian.. I think it may cause by internet connection issue.. 🤨
